# Generated by Django 3.2.7 on 2022-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncillorContactInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_id', models.CharField(max_length=200, unique=True)),
                ('councillor', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
