# Generated by Django 3.2.7 on 2022-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councillorcontactinfo',
            name='ward_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
